"""empty message

Revision ID: f6318364da3d
Revises: 9d98c9e419a0
Create Date: 2024-07-21 17:45:19.392994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6318364da3d'
down_revision = '9d98c9e419a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorites_user_id_key', ['user_id'])

    # ### end Alembic commands ###
